version: "3.9"

services:

  frontend:
    build: ../smartsite-frontend
    container_name: smartsite-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

  postgres_app:
    image: postgres:15
    container_name: smartsite-postgres-app
    restart: always
    environment:
      POSTGRES_USER: smartsite
      POSTGRES_PASSWORD: smartsite
      POSTGRES_DB: smartsite
    ports:
      - "5433:5432"
    volumes:
      - postgres_app_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: smartsite-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres_keycloak:
    image: postgres:15
    container_name: smartsite-postgres-keycloak
    restart: always
    environment:
      POSTGRES_USER: smartsite
      POSTGRES_PASSWORD: smartsite
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: smartsite-keycloak
    restart: always
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak_db
      KC_DB_USERNAME: smartsite
      KC_DB_PASSWORD: smartsite
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres_keycloak

  backend:
    build: ../smartsite-backend/smartsite-backend
    container_name: smartsite-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgres_app
      - keycloak
    env_file:
      - ../smartsite-backend/smartsite-backend/.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/smartsite
      POSTGRES_HOST: postgres_app
      POSTGRES_PORT: 5432
      POSTGRES_USER: smartsite
      POSTGRES_PASSWORD: smartsite
      POSTGRES_DB: smartsite
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      FRONTEND_URL: http://localhost:5173

volumes:
  postgres_app_data:
  mongo_data:
  postgres_keycloak_data:
  
  
